### ISSUE TITLE
Change BNO055 Power Mode

### ISSUE THREAD

**Issue by scout208** [WasabiFan/adafruit-win10-iot#2]
Hi, I can't seem to get the power mode to change after I initialized the Imu. 

Here's the code I am using:

    BNO055 Imu = new BNO055IMU();
    await Imu.Initialize();
    await Imu.SetPowerMode(PowerMode.Suspend);

Now when I call `Imu.ReadByte(BNO055Register.BNO055_PWR_MODE_ADDR)` it returns 0, so the power mode isn't being changed to suspend mode.

Is there something else that I need to do to get the power mode to change?

**Comment by scout208** [comment]
I missed the part in the datasheet that said that the BNO055 must be set to config mode before making changes to any registers. My silly mistake.

**Comment by WasabiFan** [comment]
Do you think there are changes we should be making to the library so this is more obvious? I didn't use the power modes much when working with that sensor so there may be things missing.
